[TH2-1074] update README.md
th2-net/th2-infra-operator pull request #2
Opened 2020-11-24 14:01 UTC by vdonadze

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +Together with _infra-mgr_ and _helm-operator_ it ensures synchronization of CR files from GitHub and actual resources
Please add a link to the infra-mgr repository

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +Infra operator is java implementation of Kubernetes custom resource controller. It is part of _th2 infrastructure_.
Please add a little description for `custom resource` and link to full documentation

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +Together with _infra-mgr_ and _helm-operator_ it ensures synchronization of CR files from GitHub and actual resources
Please add a link to full documentation of helm-operator

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +* Manage Vhosts, exchanges, queues, channels and user permissions on RabbitMQ
What is the source of configuration to manage?

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +* Generate GRPC configs for each resource that needs it.
Please rename gRPC and add a link to the documentation

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> +#### Main objectives
Could we add examples or links for _Th2CustomResources_, _Th2Link_, and others?

2020-11-24 14:40 UTC, Nikita-Smirnov-Exactpro commented on README.md
> + Infra operator is deployed in `service` namespace. As it needs specific configurations attached to its pod,
Please rename to infra-operator

2020-11-25 15:48 UTC, jean-michel-perli-sonsin requested changes

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +infra-operator is java implementation of Kubernetes
**The** infra-operator is **a** java implementation of Kubernetes

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +List below covers main responsibilities and objectives of this component.
**The list** below covers **the** main **duties** and objectives of this component.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +* Monitor Kubernetes events related to the _Th2CustomResources_ and Generate or modify
**It monitors** Kubernetes events related to the _Th2CustomResources_ and Generate or **it modifies**

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +corresponding Helm Releases.
**the** corresponding Helm Releases.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +* Based on config map `rabbit-mq-app-config` which is deployed by infra-mgr, creates Vhost in RabbitMQ for every schema namespace.
Based on **the** config map `rabbit-mq-app-config` which is deployed by infra-mgr, **it** creates Vhost in RabbitMQ for every schema namespace.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +* For each Vhost create user in RabbitMQ and configure its permissions.
For each Vhost **, it creates a** user in RabbitMQ and configure its permissions.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +* Based on pins described in CRs and pins described in _Th2Link_ resources declare queues in RabbitMQ.
Based on **the** pins described in CRs and **the** pins described in _Th2Link_ resources **, it declares** queues in RabbitMQ.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +* Bind queues in RabbitMQ according to _Th2Link_ resources.
**It bind** queues in RabbitMQ according to _Th2Link_ resources.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +infra-operator is a cluster-wide resource, meaning that there should be only one instance of it deployed on the cluster.
**The** infra-operator is a cluster-wide resource, meaning that there **should only be** one instance of it deployed on the cluster.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> + infra-operator is deployed in `service` namespace. As it needs specific configurations attached to its pod,
**The** infra-operator is deployed in `service` namespace. **Since** it needs specific configurations attached to its pod,

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> + deployment is done through charts by applying `/values/service.helmrelease.yaml`
**the** deployment is **performed** through charts by applying `/values/service.helmrelease.yaml`

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +infra-operator is also responsible for queues and user permission management on [RabbitMQ](https://www.rabbitmq.com/documentation.html).
**The** infra-operator is also responsible for queues and **users** permission management on [RabbitMQ](https://www.rabbitmq.com/documentation.html).

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +For more information on custom resources used in th2, and their configuration,
For more information **about** custom resources used in **th2 and** their configuration,

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +it ensures synchronization of custom resource files from GitHub and actual resources
it ensures **the** synchronization of custom resource files from GitHub and **the** actual resources

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +in Kubernetes. infra-operator uses [fabric8](https://fabric8.io/guide/) library for communication with Kubernetes.
in Kubernetes. **The** infra-operator uses [fabric8](https://fabric8.io/guide/) library for communication with Kubernetes.

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +However, as such custom components are not part of default Kubernetes installation It is infra-operator's
However, **since** such custom components are not part of **the** default Kubernetes installation **, it is** infra-operator's

2020-11-25 15:48 UTC, jean-michel-perli-sonsin commented on README.md
> +task to look over them. infra-operator monitors 5 kind of custom resources, which are defined in
task to look over them. **The** infra-operator monitors 5 kind of custom resources, which are defined in

2020-11-26 15:17 UTC, merged